# Generated by Django 5.0.6 on 2024-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='учится'),
        ),
    ]
